### ISSUE TITLE
bitbucket support

### ISSUE THREAD

**Issue by 23doors** [TomTucka/terraform-provider-circleci#17]
You seem to currently be using specifically v1 API and support for non-github VCS was added in v1.1 circleci API.

Maybe you should join forces with: https://github.com/mrolla/terraform-provider-circleci which is already working fine with bitbucket and uses v1.1 API. The biggest downside of that provider is that they are not a part of terraform registry.

**Comment by TomTucka** [comment]
@23doors I wasn't aware of that project! I'm working on a go-client for the v2 API right now.

I can do the work to update this project to use the v1.1 API in the next week or so.

**Comment by TomTucka** [comment]
Hey @23doors, `v0.3.0` should support configuring the version control system

**Comment by 23doors** [comment]
Awesome, thanks!
